jobs:
- job: VisualStudio2019TwoStep
  timeoutInMinutes: 90
  pool:
    vmImage: windows-2019
  strategy:
    matrix:
      Debug64:
        BuildPlatform: x64
        BuildConfiguration: Debug
  variables:
    VCPKG_ROOT: $(Build.SourcesDirectory)\vcpkg
  steps:
  - script: |
      perl -V
      C:\Strawberry\c\bin\perl -V
    displayName: Vcpkg

- job: VisualStudio2017
  timeoutInMinutes: 90
  pool:
    vmImage: vs2017-win2016
  strategy:
    matrix:
      Debug64:
        BuildPlatform: x64
        BuildConfiguration: Debug
  variables:
    VCPKG_ROOT: $(Build.SourcesDirectory)\vcpkg
  steps:
  - script: |
      perl -V
      C:\Strawberry\c\bin\perl -V
    displayName: Vcpkg
